#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _GABAa.c_reg(void);
extern void _GABAa.lo_reg(void);
extern void _GABAa.mod_reg(void);
extern void _IAHP.c_reg(void);
extern void _IAHP.lo_reg(void);
extern void _IAHP.mod_reg(void);
extern void _IAHP2.c_reg(void);
extern void _IAHP2.lo_reg(void);
extern void _IAHP2.mod_reg(void);
extern void _IAHP2_0403.c_reg(void);
extern void _IAHP2_0403.lo_reg(void);
extern void _IAHP2_0403.mod_reg(void);
extern void _IAHP_original.c_reg(void);
extern void _IAHP_original.lo_reg(void);
extern void _IAHP_original.mod_reg(void);
extern void _ICA.c_reg(void);
extern void _ICA.lo_reg(void);
extern void _ICA.mod_reg(void);
extern void _IT2.c_reg(void);
extern void _IT2.lo_reg(void);
extern void _IT2.mod_reg(void);
extern void _MsLN.c_reg(void);
extern void _MsLN.lo_reg(void);
extern void _MsLN.mod_reg(void);
extern void _MsLN_0403.c_reg(void);
extern void _MsLN_0403.lo_reg(void);
extern void _MsLN_0403.mod_reg(void);
extern void _cad.c_reg(void);
extern void _cad.lo_reg(void);
extern void _cad.mod_reg(void);
extern void _cad_0403.c_reg(void);
extern void _cad_0403.lo_reg(void);
extern void _cad_0403.mod_reg(void);
extern void _gabaa.c_reg(void);
extern void _gabaa.lo_reg(void);
extern void _gabaa.mod_reg(void);
extern void _gamma.c_reg(void);
extern void _gamma.lo_reg(void);
extern void _gamma.mod_reg(void);
extern void _hh.c_reg(void);
extern void _hh.lo_reg(void);
extern void _hh.mod_reg(void);
extern void _intermittent_stim.c_reg(void);
extern void _intermittent_stim.lo_reg(void);
extern void _intermittent_stim.mod_reg(void);
extern void _intermittent_stim_gaus.c_reg(void);
extern void _intermittent_stim_gaus.lo_reg(void);
extern void _intermittent_stim_gaus.mod_reg(void);
extern void _intermittent_stim_withNoise.c_reg(void);
extern void _intermittent_stim_withNoise.lo_reg(void);
extern void _intermittent_stim_withNoise.mod_reg(void);
extern void _libnrnmech.la_reg(void);
extern void _mod_func.c_reg(void);
extern void _mod_func.lo_reg(void);
extern void _normrand_test.c_reg(void);
extern void _normrand_test.lo_reg(void);
extern void _normrand_test.mod_reg(void);
extern void _pGPeA_fukuda.c_reg(void);
extern void _pGPeA_fukuda.lo_reg(void);
extern void _pGPeA_fukuda.mod_reg(void);
extern void _special_reg(void);
extern void _stim.c_reg(void);
extern void _stim.lo_reg(void);
extern void _stim.mod_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr, "\n");
  }
  _GABAa.c_reg();
  _GABAa.lo_reg();
  _GABAa.mod_reg();
  _IAHP.c_reg();
  _IAHP.lo_reg();
  _IAHP.mod_reg();
  _IAHP2.c_reg();
  _IAHP2.lo_reg();
  _IAHP2.mod_reg();
  _IAHP2_0403.c_reg();
  _IAHP2_0403.lo_reg();
  _IAHP2_0403.mod_reg();
  _IAHP_original.c_reg();
  _IAHP_original.lo_reg();
  _IAHP_original.mod_reg();
  _ICA.c_reg();
  _ICA.lo_reg();
  _ICA.mod_reg();
  _IT2.c_reg();
  _IT2.lo_reg();
  _IT2.mod_reg();
  _MsLN.c_reg();
  _MsLN.lo_reg();
  _MsLN.mod_reg();
  _MsLN_0403.c_reg();
  _MsLN_0403.lo_reg();
  _MsLN_0403.mod_reg();
  _cad.c_reg();
  _cad.lo_reg();
  _cad.mod_reg();
  _cad_0403.c_reg();
  _cad_0403.lo_reg();
  _cad_0403.mod_reg();
  _gabaa.c_reg();
  _gabaa.lo_reg();
  _gabaa.mod_reg();
  _gamma.c_reg();
  _gamma.lo_reg();
  _gamma.mod_reg();
  _hh.c_reg();
  _hh.lo_reg();
  _hh.mod_reg();
  _intermittent_stim.c_reg();
  _intermittent_stim.lo_reg();
  _intermittent_stim.mod_reg();
  _intermittent_stim_gaus.c_reg();
  _intermittent_stim_gaus.lo_reg();
  _intermittent_stim_gaus.mod_reg();
  _intermittent_stim_withNoise.c_reg();
  _intermittent_stim_withNoise.lo_reg();
  _intermittent_stim_withNoise.mod_reg();
  _libnrnmech.la_reg();
  _mod_func.c_reg();
  _mod_func.lo_reg();
  _normrand_test.c_reg();
  _normrand_test.lo_reg();
  _normrand_test.mod_reg();
  _pGPeA_fukuda.c_reg();
  _pGPeA_fukuda.lo_reg();
  _pGPeA_fukuda.mod_reg();
  _special_reg();
  _stim.c_reg();
  _stim.lo_reg();
  _stim.mod_reg();
}
